src/Entity/Galeries.php
<?php

namespace App\Entity;

use App\Utilitaire;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormFactory;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GaleriesRepository")
 */
class Galeries extends Contenus
{

    public function getImagesPath(): array
    {
        $path = [];
        try {
            $dossier = opendir("Images/Galeries/".$this->getId());
        } catch (\Exception $e) {
            return $path;
        }
        while (false !== ($fichier = readdir($dossier))) {
            if($fichier != '.' && $fichier != '..' ) {
                $path[] = '/Images/Galeries/' . $this->getId() . '/' . $fichier;
            }
        }
        return $path;
    }

    public function getNbPages() {
        try {
            $path = 'Images/Galeries/' . $this->getId();
            if(!file_exists('Images/Galeries/' . $this->getId()))
                mkdir($path);
            $files = array_diff(scandir($path), array('..', '.'));
        } catch (\Exception $e) {
            return 1;
        }
        $nbPage = intval(sizeof($files)/10);
        if(sizeof($files)%10 != 0)
            $nbPage++;
        return $nbPage;
    }

    public function getType()
    {
        return "galerie";
    }

    public function genererRendu(\Twig_Environment $twig, FormFactory $form, ObjectManager $em, Request $request): ?string
    {
        $f = $this->createForm($form);
        $f->handleRequest($request);

        if ($f->isSubmitted() && $f->isValid() && $request->request->has("texte".$this->getId())) {
            $this->executeForm($f,$em);
        }

        $param = $em->getRepository(Parametres::class)->find(0);

        $this->html = $twig->render('contenu/' . $this->getType() .
            '.html.twig', [
            "t" => $this,
            "f" => $f->createView(),
            "p" => $param
        ]);
        return null;

    }

    public function createForm(FormFactory $form): FormInterface
    {
        $form = $form->createNamedBuilder("texte".$this->getId());
        $form->add("titre", TextType::class, ['data' => $this->getTitre(), 'label' => false, 'attr' => ['data-length' => 100, 'maxlength' => 100, 'class' => "text-input"]])
            ->add('img', FileType::class, ['label' => 'Image', 'multiple' => true,'attr' => [
                'accept' => 'image/*',
                'multiple' => 'multiple'
            ]])
            ->add("valider", SubmitType::class, ['label' => 'Valider']);
        return $form->getForm();
    }

    public function executeForm(FormInterface $form, ObjectManager $em)
    {
        $data = $form->getData();
        /** @var UploadedFile[] $files */
        $files = $data['img'];
        $this->setTitre($data['titre']);
        if (sizeof($files) != 0){
            array_map('unlink', glob("Images/Galeries/". $this->getId() . '/*'));
            foreach ($files as $file){
                $file->move("Images/Galeries/" . $this->getId() . "/", $file->getClientOriginalName());
            }
        }
        $em->flush();
    }

    public function onDelete()
    {
        Utilitaire::deleteDirectory("Images/Galeries/" . $this->getId());
    }
}

src/Entity/Inscription.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\InscriptionRepository")
 */
class Inscription
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $dateNaissance;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $categorie;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    private $club;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $licenceCertif;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $codePostal;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $ville;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Circuit", inversedBy="inscriptions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $circuit;

    /**
     * @ORM\Column(type="string", length=16, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="boolean")
     */
    private $payer;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $mail;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Course", inversedBy="inscriptions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $course;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\OptionInscri", mappedBy="inscription", orphanRemoval=true, cascade={"persist"})
     */
    private $optionInscris;

    public function __construct()
    {
        $this->optionInscris = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $dateNaissance): self
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getClub(): ?string
    {
        return $this->club;
    }

    public function setClub(?string $club): self
    {
        $this->club = $club;

        return $this;
    }

    public function getLicenceCertif(): ?string
    {
        return $this->licenceCertif;
    }

    public function setLicenceCertif(string $licenceCertif): self
    {
        $this->licenceCertif = $licenceCertif;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->codePostal;
    }

    public function setCodePostal(string $codePostal): self
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCircuit(): ?Circuit
    {
        return $this->circuit;
    }

    public function setCircuit(?Circuit $circuit): self
    {
        $this->circuit = $circuit;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getPayer(): ?bool
    {
        return $this->payer;
    }

    public function setPayer(bool $payer): self
    {
        $this->payer = $payer;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(?string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getCourse(): ?Course
    {
        return $this->course;
    }

    public function setCourse(?Course $course): self
    {
        $this->course = $course;

        return $this;
    }

    /**
     * @return Collection|OptionInscri[]
     */
    public function getOptionInscris(): Collection
    {
        return $this->optionInscris;
    }

    public function addOptionInscri(OptionInscri $optionInscri): self
    {
        if (!$this->optionInscris->contains($optionInscri)) {
            $this->optionInscris[] = $optionInscri;
            $optionInscri->setInscription($this);
        }

        return $this;
    }

    public function removeOptionInscri(OptionInscri $optionInscri): self
    {
        if ($this->optionInscris->contains($optionInscri)) {
            $this->optionInscris->removeElement($optionInscri);
            // set the owning side to null (unless already changed)
            if ($optionInscri->getInscription() === $this) {
                $optionInscri->setInscription(null);
            }
        }

        return $this;
    }

    public function getPrix() {
        $total = $this->circuit->getPrix();
        /** @var OptionInscri $option */
        foreach ($this->optionInscris as $option) {
            $total += floatval($option->getItem()->getPrice())*$option->getQuantite();
        }
        return $total;
    }
}

src/Entity/Liens.php
<?php

namespace App\Entity;

use App\Utilitaire;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormFactory;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LiensRepository")
 */
class Liens extends Contenus
{
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;

    public function getChemin(): ?string
    {
        return "/Documents/". $this->getId() . '/' . $this->getNom();
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getType()
    {
        return "liens";
    }

    public function genererRendu(\Twig_Environment $twig, FormFactory $form, ObjectManager $em, Request $request): ?string
    {
        $f = $this->createForm($form);
        $f->handleRequest($request);

        if ($f->isSubmitted() && $f->isValid() && $request->request->has("texte".$this->getId())) {
            $this->executeForm($f,$em);
        }

        $param = $em->getRepository(Parametres::class)->find(0);

        $this->html = $twig->render('contenu/' . $this->getType() .
            '.html.twig', [
            "t" => $this,
            "f" => $f->createView(),
            "p" => $param
        ]);
        return null;

    }

    public function createForm(FormFactory $form): FormInterface
    {
        $form = $form->createNamedBuilder("texte".$this->getId());
        $form->add("titre", TextType::class, ['data' => $this->getTitre(), 'label' => false, 'attr' => ['data-length' => 100, 'maxlength' => 100, 'class' => "text-input"]])
            ->add('img', FileType::class, ['label' => 'Image'])
            ->add("valider", SubmitType::class, ['label' => 'Valider']);
        return $form->getForm();
    }

    public function executeForm(FormInterface $form, ObjectManager $em)
    {
        $data = $form->getData();
        /** @var UploadedFile $file */
        $file = $data['img'];
        $this->nom = ($file->getClientOriginalName());
        array_map('unlink', glob("Documents/". $this->getId() . '/*'));
        $file->move("Documents/". $this->getId() . '/', $this->getNom());
        $this->setTitre($data['titre']);
        $em->flush();
    }

    public function onDelete()
    {
        Utilitaire::deleteDirectory("Documents/". $this->getId());
    }
}

templates/contenu/engagement.html.twig
{% extends 'contenu/contenu.html.twig' %}
{% set c = t.course %}

{%  block blockPageAdmin %}
    <h1 class="col s12 couleur  no-margin paddingTop10 paddingBot10 bordureTop">
        <div class="col s6 couleur brightCouleur lighten-4 titreForm">
            {{ form_row(f.titre) }}
        </div>
        <div class="col s6 right-align paddingTop10">
            <p>Engagement</p>
        </div>
    </h1>
    <div class="row">
        <div class="col s10 offset-s1">
            <p>(Entrée: Retour à la ligne avec espace   |   Shift + Entrée : Retour sans espace)</p>
            {{ form_row(f.comm) }}
        </div>
    </div>

    <div class="row center-align paddingBot15 ">
        {{ form_row(f.valider) }}
    </div>
{%  endblock blockPageAdmin %}

{% block otherForm %}
    <div class="col s6 paddingBot15 ">
        <div class="row center-align">
            <!-- Modal Trigger -->
            <a class="couleur waves-effect waves-light btn modal-trigger" href="#modalCircuitEng{{ t.id }}">Ajouter un circuit</a>
        </div>
        <div class="row paddingTop15">
            {% for circuit in t.course.circuits %}
                <div class="row shadowLight marginLeft25 marginRight10 bordureArrondit marginTop5 marginBot5 paddingTop5 paddingBot5">
                    <div class="col s9 offset-s1 paddingTop3">
                        <div class="col s6">
                            Nom : {{ circuit.nom }}
                        </div>
                        <div class="col s3">
                            Prix : {{ circuit.prix }} €
                        </div>
                        <div class="col s3">
                            Dist : {{ circuit.distance }} km
                        </div>
                    </div>
                    <div class="col s1">
                        <i class="material-icons delOption actionDel" idToRem="{{ circuit.id }}" info="circuit">delete</i>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="col s6 paddingBot15 ">
        <div class="row center-align">
            <!-- Modal Trigger -->
            <a class="couleur waves-effect waves-light btn modal-trigger" href="#modalOptionEng{{ t.id }}">Ajouter une option</a>
        </div>

        <div class="row paddingTop15">
            {% for option in t.course.optionCourses %}
                <div class="row shadowLight marginLeft10 marginRight25 bordureArrondit marginTop5 marginBot5 paddingTop5 paddingBot5">
                    <div class="col s9 offset-s1 paddingTop3">
                        <div class="col s6">
                            Nom : {{ option.titre }}
                        </div>
                        <div class="col s3">
                            Prix : {{ option.prix }} €
                        </div>
                        <div class="col s3">
                            Type : {{ option.type }}
                        </div>
                    </div>
                    <div class="col s1">
                        <i class="material-icons delOption actionDel" idToRem="{{ option.id }}" info="option">delete</i>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <!-- Modal Structure -->
    <div id="modalCircuitEng{{ t.id }}" class="modal">
        <div class="modal-content col s6 offset-s3">
            <h4>Ajouter un circuit</h4>
            {{ form_start(formCircuit) }}
            {{ form(formCircuit) }}
            {{ form_end(formCircuit) }}
        </div>
        <div class="modal-footer">
            <a href="#!" class="modal-close waves-effect waves-green btn-flat">Annuler</a>
        </div>
    </div>

    <!-- Modal Structure -->
    <div id="modalOptionEng{{ t.id }}" class="modal">
        <div class="modal-content col s6 offset-s3">
            <h4>Ajouter une option</h4>
            {{ form_start(formOption) }}
            <div class="center-align">
                {{ form_row(formOption.quantite) }}
            </div>
            {{ form_end(formOption) }}
        </div>
        <div class="modal-footer">
            <a href="#!" class="modal-close waves-effect waves-green btn-flat">Annuler</a>
        </div>
    </div>

    {% include 'JSTwig/delOnCourseJS.html.twig' with {'t' : t} %}
    <script type="text/javascript">
        $(".jsReplace").attr("type","number");
    </script>

    <table class="table bordureTop striped highlight">
        <thead class="couleur">
        <tr>
            <td>Nom</td>
            <td>Prénom</td>
            <td>Prix</td>
            <td>Date de naissance</td>
            <td>Catégorie</td>
            <td>Club</td>
            <td>Licence ou certificat</td>
            <td>Adresse</td>
            <td>Téléphone</td>
            <td>Email</td>
            <td>Circuit</td>
            <td>Options (qte)</td>
        </tr>
        </thead>
        <tbody>
        {% for i in c.inscriptions %}
            <tr>
                <td>{{ i.nom}}</td>
                <td>{{ i.prenom }}</td>
                <td{% if i.payer %} class="payer"{% endif %}>{{ i.prix }}€</td>
                <td>{{ i.dateNaissance.format("d-m-Y") }}</td>
                <td>{{ i.categorie }}</td>
                <td>{{ i.club }}</td>
                <td>{{ i.licenceCertif }}</td>
                <td>{{ i.adresse }} {{ i.codePostal }} {{ i.ville }}</td>
                <td>{{ i.telephone }}</td>
                <td>{{ i.mail }}</td>
                <td>{{ i.circuit.nom }}</td>
                <td>{% for o in i.optionInscris %} {{ o.texte }}{% endfor %}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock otherForm %}

{%  block blockPage %}
    <h5 class="col s12 blue lighten-2 no-margin paddingTop10 paddingBot10 bordureTop">{{ c.nom }}</h5>
    {% autoescape false %}
        <div class="col s12 paddingTop10 paddingBot10">{{ c.description }}</div>
    {% endautoescape %}
    <div class="col s12  no-margin paddingTop5 paddingBot5 bordureBot">
        {{ form_start(formInscription) }}
        {% set compt = 0 %}
        {% for nom, g in formInscription.children if nom not in ['payer','valider','course'] %}
            {% if compt is divisible by(3) %}
                <div class="row hide-on-med-and-down"></div>
            {% elseif compt is divisible by(2) %}
                <div class="row hide-on-small-only hide-on-large-only"></div>
            {% endif %}
            <div class="col l4 m6 s12">
                {{ form_row(g) }}
            </div>
            {% set compt = compt+1 %}
        {% endfor %}

        <div class="col s12 center-align">
            {{ form_row(formInscription.valider) }}
        </div>
        {{ form_end(formInscription, {'render_rest': false}) }}
    </div>
{%  endblock blockPage %}

templates/contenu/galerie.html.twig
{% extends 'contenu/contenu.html.twig' %}

{%  block blockPageAdmin %}
    <h1 class="col s12 couleur  no-margin paddingTop10 paddingBot10 bordureTop">
        <div class="col s6 couleur brightCouleur lighten-4 titreForm">
            {{ form_row(f.titre) }}
        </div>
        <div class="col s6 right-align paddingTop10">
            <p>Galerie</p>
        </div>
    </h1>
    <div class="col s12 no-padding couleur">
        <ul class="tabs couleur brightCouleur">
            {% for page in 1..t.nbPages %}
                <li class="tab col s3 white-text"><a href="#tab{{ page }}" class="white-text">Page {{ page }}</a></li>
            {% endfor %}
        </ul>
    </div>
    {% if t.imagesPath is empty %}
    <div>
        {% endif %}
        {% for path in t.imagesPath %}
        {% if loop.index0 is divisible by(10) %}
        {% if loop.index0 != 0 %}
    </div>
    {% endif %}
    <div id="tab{{ loop.index0/10 + 1 }}" class="col s12 heightTab">
        {% endif %}
        <div class="col s4 {% if loop.index0 is odd %} offset-s1 {% else %} offset-s2 {% endif %} paddingTop10">
            <img class="materialboxed col s12" src="{{ path }}" >
        </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col s10 offset-s1">
            {{ form_row(f.img) }}
        </div>
    </div>
    <div class="row center-align photoLoad">
        {{ form_row(f.valider) }}
    </div>

    <script type="application/javascript">
        $(".photoLoad").parents().submit(function () {
            $(".loadImage").css("display", "block");
        })
    </script>

    <div class="row center-align paddingTop10 ">
        <div style="display: none" class="loadImage">
            <p>L'opération peut prendre quelques minutes</p>
            <div class="preloader-wrapper small active center-align">
                <div class="spinner-layer spinner-green-only">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div><div class="gap-patch">
                        <div class="circle"></div>
                    </div><div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{%  endblock blockPageAdmin %}

{%  block blockPage %}
    <h5 class="col s12 couleur no-margin paddingTop10 paddingBot10 bordureTop">{{ t.titre }}</h5>
    <div class="col s12 no-padding couleur">
        <ul class="tabs couleur brightCouleur">
            {% for page in 1..t.nbPages %}
                <li class="tab col s3 white-text"><a href="#tab{{ page }}" class="white-text">Page {{ page }}</a></li>
            {% endfor %}
        </ul>
    </div>
    {% for path in t.imagesPath %}
        {% if loop.index0 is divisible by(10) %}
            {% if loop.index0 != 0 %}
                </div>
            {% endif %}
            <div id="tab{{ loop.index0/10 + 1 }}" class="col s12 heightTab">
        {% endif %}
        <div class="col s4 {% if loop.index0 is odd %} offset-s1 {% else %} offset-s2 {% endif %} paddingTop10">
            <img class="materialboxed col s12" src="{{ path }}" >
        </div>
    {% endfor %}
    </div>

{%  endblock blockPage %}

{%  block blockContenuAdmin %}
    {#<div class="container bordure {{ p.couleur }} lighten-2 paddingTop35 paddingRight35 paddingLeft35 col l4 offset-l4 m6 offset-m3 s12">#}
    <div class="slider">
        <ul class="slides shadow">
            {% for image in t.contenuses %}
                <li>
                    <img src="{{ image.chemin }}">
                </li>
            {% endfor %}
        </ul>
    </div>
{%  endblock blockContenuAdmin %}

{%  block blockContenu %}
    {#<div class="container bordure {{ p.couleur }} lighten-2 paddingTop35 paddingRight35 paddingLeft35 col l4 offset-l4 m6 offset-m3 s12">#}
    <div class="slider">
        <ul class="slides shadow">
            {% for image in t.contenuses %}
                <li>
                    <img src="{{ image.chemin }}">
                </li>
            {% endfor %}
        </ul>
    </div>
{%  endblock blockContenu %}

templates/contenu/image.html.twig
{% extends 'contenu/contenu.html.twig' %}

{% block blockPageAdmin %}
    <h1 class="col s12 couleur  no-margin paddingTop10 paddingBot10 bordureTop">
        <div class="col s6 brightCouleur lighten-4 titreForm">
            {{ form_row(f.titre) }}
        </div>
        <div class="col s6 right-align paddingTop10">
            <p>Image</p>
        </div>
    </h1>
    {% if t.nom is not null %}
        <div class="row">
            <div class="col s12 center-align flexHor">
            <img class="materialboxed center paddingTop15" width="100" src="{{ t.chemin }}">
            </div>
        </div>
    {% endif %}

    <div class="row">
        <div class="col s10 offset-s1">
            {{ form_row(f.img) }}
        </div>
    </div>
    <div class="row center-align">
        {{ form_row(f.valider) }}
    </div>
{% endblock blockPageAdmin %}

{% block blockPage %}
    <h1 class="col s12 couleur no-margin paddingTop10 paddingBot10 bordureTop valign-wrapper">
        {{ t.titre }}
    </h1>
        <img class="materialboxed paddingTop10 col s8 offset-s2" src="{{ t.chemin }}">
{% endblock blockPage %}

{% block blockContenuAdmin %}
    {% autoescape false %}
        <div class="col s12 paddingTop10 paddingBot10">{{ t.commentaire }}</div>
    {% endautoescape %}
{% endblock blockContenuAdmin %}

{% block blockContenu %}
    <img class="materialboxed col s10 offset-s1" src="{{ t.chemin }}">
{% endblock blockContenu %}

templates/contenu/partenaires.html.twig
{% extends 'contenu/contenu.html.twig' %}

{%  block blockPageAdmin %}
    <h1 class="col s12 couleur  no-margin paddingTop10 paddingBot10 bordureTop">
        <div class="col s6 couleur brightCouleur lighten-4 titreForm">
            {{ form_row(f.titre) }}
        </div>
        <div class="col s6 right-align paddingTop10">
            <p>Partenaires</p>
        </div>
    </h1>
        {% for path in t.imagesPath %}
        <div class="col s1 paddingTop10">
            <img class="responsive-img" src="{{ path }}" >
        </div>
        {% endfor %}
    <div class="row">
        <div class="col s10 offset-s1">
            {{ form_row(f.img) }}
        </div>
    </div>
    <div class="row center-align photoLoad">
        {{ form_row(f.valider) }}
    </div>

    <script type="application/javascript">
        $(".photoLoad").parents().submit(function () {
            $(".loadImage").css("display", "block");
        })
    </script>

    <div class="row center-align paddingTop10 ">
        <div style="display: none" class="loadImage">
            <p>L'opération peut prendre quelques minutes</p>
            <div class="preloader-wrapper small active center-align">
                <div class="spinner-layer spinner-green-only">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div><div class="gap-patch">
                        <div class="circle"></div>
                    </div><div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{%  endblock blockPageAdmin %}

{%  block blockPage %}
    <h5 class="col s12 couleur no-margin paddingTop10 paddingBot10 bordureTop">{{ t.titre }}</h5>
    <div class="marginLeft20 marginRight20">
    <div class="row">
    {% for path in t.imagesPath %}
        {% if loop.index0 % 6 == 0 and loop.index0 != 0 %}
        </div>
        <div class="row">
        {% endif %}
        <div class="col s2 paddingTop10" >
            <div class="valign" style="height: 150px;">
            <img class="responsive-img sizeImg" width="250"  style="vertical-align:middle;" src="{{ path }}" >
            </div>
        </div>
    {% endfor %}
    </div>
    </div>
{%  endblock blockPage %}

{%  block blockContenuAdmin %}
    {#<div class="container bordure {{ p.couleur }} lighten-2 paddingTop35 paddingRight35 paddingLeft35 col l4 offset-l4 m6 offset-m3 s12">#}
    <div class="slider">
        <ul class="slides shadow">
            {% for image in t.contenuses %}
                <li>
                    <img src="{{ image.chemin }}">
                </li>
            {% endfor %}
        </ul>
    </div>
{%  endblock blockContenuAdmin %}

{%  block blockContenu %}
    {#<div class="container bordure {{ p.couleur }} lighten-2 paddingTop35 paddingRight35 paddingLeft35 col l4 offset-l4 m6 offset-m3 s12">#}
    <div class="slider">
        <ul class="slides shadow">
            {% for image in t.contenuses %}
                <li>
                    <img src="{{ image.chemin }}">
                </li>
            {% endfor %}
        </ul>
    </div>
{%  endblock blockContenu %}